Repository Heroic-Games-Launcher/HeroicGamesLauncher, pull requests merged in 2021-03, with the labels that each got.

#243 New Setting to Add Custom Wine/Proton binary
  electron/main.ts
  electron/types.ts
  electron/utils.ts
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/hu/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  src/App.css
  src/components/Settings/WineSettings.tsx
  src/components/Settings/index.tsx
  src/types.ts
Labels: translations needed

#231 Implement offline functionalities.
  electron/main.ts
  electron/types.ts
  electron/utils.ts
  package.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/hu/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  src/components/GamePage/GamePage.tsx
  src/components/Settings/OtherSettings.tsx
  src/components/Settings/index.tsx
  src/types.ts
  yarn.lock
Labels: ready for merge

#244 refactor: Sort imports, exports, keys, etc alphabetically. Disallow trailing whitespace and dangling commas.
  .eslintrc
  electron/legendary_utils/library.ts
  electron/main.ts
  electron/types.ts
  electron/utils.ts
  package.json
  src/App.test.tsx
  src/App.tsx
  src/components/GamePage/GamePage.tsx
  src/components/GamePage/GamesSubmenu.tsx
  src/components/Library.tsx
  src/components/Login.tsx
  src/components/NavBar.tsx
  src/components/Settings/GeneralSettings.tsx
  src/components/Settings/OtherSettings.tsx
  src/components/Settings/SyncSaves.tsx
  src/components/Settings/Tools.tsx
  src/components/Settings/WineSettings.tsx
  src/components/Settings/index.tsx
  src/components/UI/GameCard.tsx
  src/components/UI/Header.tsx
  src/components/UI/InfoBox.tsx
  src/components/UI/LanguageSelector.tsx
  src/components/UI/SearchBar.tsx
  src/components/UI/ToggleSwitch.tsx
  src/components/UI/UserSelector.tsx
  src/components/utls.ts
  src/helper.ts
  src/hooks/useToggle.ts
  src/index.tsx
  src/state/ContextProvider.tsx
  src/state/GlobalState.tsx
  src/types.ts
  yarn.lock
Labels: ready for merge

#258 Fix: Not starting on new installations
  .gitignore
  electron/utils.ts
  package.json
  src/components/Settings/index.tsx
Labels: ready for merge

#267 README: General improvements.
  README.md
Labels: documentation
