Repository Heroic-Games-Launcher/HeroicGamesLauncher, pull requests merged in 2021-06, with the labels that each got.

#399 Update all packages.
  .husky/.gitignore
  .husky/post-checkout
  .husky/post-merge
  .husky/pre-commit
  .husky/pre-push
  jest.config.js
  package.json
  yarn.lock
Labels: pr:ready-to-merge

#400 ci: Switch to Node 14 for all tasks, don't report coverage (for now).
  .github/workflows/build.yml
  .github/workflows/draft-release.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: pr:ready-to-merge

#404 Some Fixes, Feedback and UI improvements
  README.md
  electron/constants.ts
  electron/games.ts
  electron/legendary_utils/library.ts
  electron/main.ts
  electron/protocol.ts
  electron/utils.ts
  i18next-parser.config.js
  package.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/gamepage.json
  public/locales/el/login.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/hu/translation.json
  public/locales/it/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/tr/translation.json
  src/components/Navbar/components/UserSelector/index.tsx
  src/components/UI/Header/index.tsx
  src/components/UI/LanguageSelector/index.tsx
  src/components/utils.test.ts
  src/components/utils.ts
  src/helpers/helpers.test.ts
  src/helpers/index.ts
  src/helpers/library.ts
  src/index.tsx
  src/screens/Game/GamePage/index.tsx
  src/screens/Game/GameSubMenu/index.tsx
  src/screens/Library/components/GameCard/index.tsx
  src/screens/Settings/components/GeneralSettings/index.tsx
  src/screens/Settings/components/SyncSaves/index.tsx
  src/screens/Settings/components/Tools/index.tsx
  src/screens/Settings/components/WineSettings/index.tsx
  src/screens/Settings/index.css
  src/state/GlobalState.tsx
  src/types.ts
  yarn.lock
Labels: pr:ready-to-merge

#416 ci: Upload artifacts for PRs.
  .github/workflows/build.yml
Labels: pr:ready-for-review

#426 backend: Minor fix for lastPlay log not opening.
  electron/main.ts
Labels: pr:ready-to-merge

#337 backend: Implement logging using Winston.
  .gitignore
  electron/logger.ts
  electron/main.ts
  package.json
  yarn.lock
Labels: pr:ready-to-merge

#442 Use $SHELL instead of bash in Linux and Mac
  electron/constants.ts
Labels: pr:ready-for-review

#443 Add Desktop shortcuts(backend)
  electron/legendary/games.ts
  electron/types.ts
Labels: pr:ready-for-review

#456 Translations update from Weblate
  public/locales/ca/login.json
  public/locales/de/gamepage.json
  public/locales/de/login.json
  public/locales/de/translation.json
  public/locales/fr/gamepage.json
  public/locales/fr/login.json
  public/locales/fr/translation.json
  public/locales/it/gamepage.json
  public/locales/it/translation.json
Labels: pr:ready-for-review

#454 os/windows: Windows improvements
  electron/main.ts
  src/components/UI/ToggleSwitch/index.tsx
  src/screens/Settings/components/GeneralSettings/index.test.tsx
  src/screens/Settings/components/GeneralSettings/index.tsx
  src/state/ContextProvider.tsx
  src/types.ts
Labels: pr:ready-for-review

#429 Add Discord RPC Support
  electron/legendary/games.ts
  electron/types.ts
  package.json
  src/screens/Settings/components/GeneralSettings/index.test.tsx
  src/screens/Settings/components/GeneralSettings/index.tsx
  src/screens/Settings/index.tsx
  src/test_helpers/testTypes.ts
  src/types.ts
  yarn.lock
Labels: pr:ready-for-review

#413 README: Minor fixes and clarifications.
  README.md
Labels: documentation, pr:ready-for-review
