Repository Heroic-Games-Launcher/HeroicGamesLauncher, pull requests merged in 2022-05, with the labels that each got.

#1249 [UI] Add options to sort games by title and status
  .eslintrc
  electron/legendary/library.ts
  package.json
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/components/UI/ActionIcons/index.tsx
  src/screens/Library/index.tsx
  yarn.lock
Labels: pr:ready-for-review

#1252 Refactor/handle game status update
  electron/gog/games.ts
  electron/legendary/games.ts
  src/state/GlobalState.tsx
Labels: pr:ready-for-review

#1254 [Tech] Eslint Updates + Fix GOG Installing
  .eslintignore
  .eslintrc
  electron/config.ts
  electron/game_config.ts
  electron/gog/games.ts
  electron/gog/library.ts
  electron/gog/user.ts
  electron/launcher.ts
  electron/legendary/games.ts
  electron/legendary/library.ts
  electron/main.ts
  electron/tools.ts
  electron/wine-manager/ipc_handler.ts
  src/App.tsx
  src/components/UI/ActionIcons/index.tsx
  src/helpers/index.ts
  src/helpers/library.ts
  src/screens/Game/GamePage/index.tsx
  src/screens/Game/GameSubMenu/index.tsx
  src/screens/Library/components/GameCard/index.tsx
  src/screens/Library/components/InstallModal/index.tsx
  src/screens/Library/index.tsx
  src/screens/Login/components/SIDLogin/index.tsx
  src/screens/Login/index.tsx
  src/screens/Settings/components/AdvancedSettings/index.tsx
  src/screens/Settings/components/GeneralSettings/index.tsx
  src/screens/Settings/components/OtherSettings/index.tsx
  src/screens/Settings/components/SyncSaves/index.tsx
  src/screens/Settings/components/Tools/index.tsx
  src/screens/Settings/components/WineSettings/index.tsx
  src/screens/WineManager/index.tsx
  src/state/ContextProvider.tsx
  tsconfig.eslint.json
Labels: pr:ready-for-review

#1256 Refactor: Push progress updates for install/update from the backend
  electron/gog/games.ts
  electron/gog/library.ts
  electron/legendary/games.ts
  electron/legendary/library.ts
  electron/main.ts
  src/helpers/library.ts
  src/hooks/hasProgress.ts
  src/screens/Game/GamePage/index.tsx
  src/screens/Library/components/GameCard/index.tsx
  src/types.ts
Labels: pr:ready-for-review

#1265 [UI] Add basic themes support
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/App.css
  src/App.tsx
  src/components/UI/Dialog/index.css
  src/components/UI/Sidebar/components/SidebarUtils/index.css
  src/components/UI/Sidebar/index.css
  src/index.css
  src/screens/Login/components/Runner/index.css
  src/screens/Login/index.css
  src/screens/Settings/components/GeneralSettings/index.tsx
  src/state/ContextProvider.tsx
  src/state/GlobalState.tsx
  src/themes.css
  src/types.ts
Labels: pr:ready-for-review

#1277 Use vertical_image value only if present
  electron/gog/library.ts
Labels: pr:ready-for-review

#1270 [UI/UX] Add Platform selection on Install dialog
  electron/games.ts
  electron/gog/games.ts
  electron/gog/library.ts
  electron/legendary/library.ts
  electron/main.ts
  electron/types.ts
  electron/utils.ts
  package.json
  public/locales/bg/gamepage.json
  public/locales/ca/gamepage.json
  public/locales/cs/gamepage.json
  public/locales/de/gamepage.json
  public/locales/el/gamepage.json
  public/locales/en/gamepage.json
  public/locales/es/gamepage.json
  public/locales/et/gamepage.json
  public/locales/fa/gamepage.json
  public/locales/fi/gamepage.json
  public/locales/fr/gamepage.json
  public/locales/gl/gamepage.json
  public/locales/hr/gamepage.json
  public/locales/hu/gamepage.json
  public/locales/id/gamepage.json
  public/locales/it/gamepage.json
  public/locales/ja/gamepage.json
  public/locales/ko/gamepage.json
  public/locales/ml/gamepage.json
  public/locales/nl/gamepage.json
  public/locales/pl/gamepage.json
  public/locales/pt/gamepage.json
  public/locales/pt_BR/gamepage.json
  public/locales/ru/gamepage.json
  public/locales/sv/gamepage.json
  public/locales/ta/gamepage.json
  public/locales/tr/gamepage.json
  public/locales/uk/gamepage.json
  public/locales/vi/gamepage.json
  public/locales/zh_Hans/gamepage.json
  public/locales/zh_Hant/gamepage.json
  src/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/helpers/index.ts
  src/helpers/library.ts
  src/screens/Game/GamePage/index.tsx
  src/screens/Game/GameSubMenu/index.tsx
  src/screens/Library/components/GameCard/index.tsx
  src/screens/Library/components/GamesList/index.tsx
  src/screens/Library/components/InstallModal/index.tsx
  src/screens/Settings/components/GeneralSettings/index.tsx
  src/screens/Settings/index.tsx
  src/state/GlobalState.tsx
  src/types.ts
  yarn.lock
Labels: pr:ready-for-review

#1281 [UI/UX] Add Accessibility Screen
  electron/constants.ts
  electron/main.ts
  package.json
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/App.css
  src/App.tsx
  src/assets/settings-sharp.svg
  src/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/components/UI/Sidebar/index.css
  src/components/UI/ThemeSelector/index.tsx
  src/index.css
  src/screens/Accessibility/index.css
  src/screens/Accessibility/index.tsx
  src/screens/Game/GamePage/index.css
  src/screens/Game/GamePage/index.tsx
  src/screens/Game/GameSubMenu/index.css
  src/screens/Library/components/GameCard/index.css
  src/screens/Library/components/GameCard/index.tsx
  src/screens/Settings/components/AdvancedSettings/index.tsx
  src/screens/Settings/components/GeneralSettings/index.tsx
  src/screens/Settings/components/SyncSaves/index.tsx
  src/screens/Settings/components/WineSettings/index.tsx
  src/screens/Settings/index.css
  src/screens/WineManager/components/WineItem/index.css
  src/screens/WineManager/components/WineItem/index.tsx
  src/state/ContextProvider.tsx
  src/state/GlobalState.tsx
  src/types.ts
  yarn.lock
Labels: pr:ready-for-review

#981 [Linux] Wine-Manager UI update
  electron/wine-manager/ipc_handler.ts
  electron/wine-manager/utils.ts
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/zh_Hant/translation.json
  src/screens/WineManager/components/WineItem/index.css
  src/screens/WineManager/components/WineItem/index.tsx
  src/screens/WineManager/index.css
  src/screens/WineManager/index.tsx
  src/state/GlobalState.tsx
Labels: pr:wip

#1306 Refactor: Handle login in a single place
  electron/gog/user.ts
  electron/legendary/user.ts
  electron/main.ts
  src/App.tsx
  src/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/components/UI/Sidebar/components/SidebarUtils/index.tsx
  src/screens/Game/GamePage/index.tsx
  src/screens/Library/index.tsx
  src/screens/Login/components/Runner/index.tsx
  src/screens/Login/components/SIDLogin/index.tsx
  src/screens/Login/index.tsx
  src/screens/WebView/index.tsx
  src/state/ContextProvider.tsx
  src/state/GlobalState.tsx
  src/types.ts
Labels: pr:ready-for-review

#1314 Fixes typos, markdown
  README.md
Labels: pr:ready-to-merge

#1267 A lot of rendering refactors related to libraries (and a few extras)
  electron/legendary/library.ts
  src/components/UI/Header/index.tsx
  src/index.tsx
  src/screens/Library/components/GameCard/index.tsx
  src/screens/Library/index.tsx
  src/state/ContextProvider.tsx
  src/state/GlobalState.tsx
  src/types.ts
Labels: pr:ready-to-merge

#1278 Update README.md
  README.md
Labels: pr:ready-to-merge

#1311 [UI] Add accessibility option to show all game tiles in color
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/screens/Accessibility/index.tsx
  src/screens/Library/components/GameCard/index.css
  src/screens/Library/components/GameCard/index.tsx
  src/state/ContextProvider.tsx
  src/state/GlobalState.tsx
  src/types.ts
Labels: pr:ready-to-merge

#1335 [Fix] Check for game updates before launch
  electron/launcher.ts
  electron/legendary/games.ts
  src/helpers/library.ts
  src/screens/Game/GamePage/index.tsx
  src/screens/Library/components/GameCard/index.tsx
  src/state/GlobalState.tsx
Labels: pr:ready-for-review

#1324 [UX] Open main window on tray double click
  electron/main.ts
Labels: pr:ready-to-merge

#1315 Refactor: Form elements
  src/App.css
  src/components/UI/LanguageSelector/index.tsx
  src/components/UI/SelectField/index.css
  src/components/UI/SelectField/index.tsx
  src/components/UI/TextInputField/index.css
  src/components/UI/TextInputField/index.tsx
  src/components/UI/TextInputWithIconField/index.tsx
  src/components/UI/ThemeSelector/index.tsx
  src/components/UI/ToggleSwitch/index.css
  src/components/UI/ToggleSwitch/index.tsx
  src/components/UI/index.tsx
  src/screens/Accessibility/index.css
  src/screens/Accessibility/index.tsx
  src/screens/Game/GamePage/index.tsx
  src/screens/Library/components/InstallModal/index.css
  src/screens/Library/components/InstallModal/index.tsx
  src/screens/Login/index.css
  src/screens/Login/index.tsx
  src/screens/Settings/components/AdvancedSettings/index.tsx
  src/screens/Settings/components/GeneralSettings/index.tsx
  src/screens/Settings/components/LogSettings/index.css
  src/screens/Settings/components/LogSettings/index.tsx
  src/screens/Settings/components/OtherSettings/index.tsx
  src/screens/Settings/components/SyncSaves/index.tsx
  src/screens/Settings/components/WineSettings/index.tsx
  src/screens/Settings/index.css
  src/screens/Settings/index.tsx
  src/screens/WineManager/components/WineItem/index.tsx
  src/state/ContextProvider.tsx
  src/state/GlobalState.tsx
  src/types.ts
Labels: pr:ready-to-merge

#1337 [UI] Show processing files message after download finished
  electron/utils.ts
  package.json
  public/locales/bg/gamepage.json
  public/locales/ca/gamepage.json
  public/locales/cs/gamepage.json
  public/locales/de/gamepage.json
  public/locales/el/gamepage.json
  public/locales/en/gamepage.json
  public/locales/es/gamepage.json
  public/locales/es/translation.json
  public/locales/et/gamepage.json
  public/locales/fa/gamepage.json
  public/locales/fa/translation.json
  public/locales/fi/gamepage.json
  public/locales/fr/gamepage.json
  public/locales/gl/gamepage.json
  public/locales/hr/gamepage.json
  public/locales/hu/gamepage.json
  public/locales/id/gamepage.json
  public/locales/it/gamepage.json
  public/locales/ja/gamepage.json
  public/locales/ko/gamepage.json
  public/locales/ko/translation.json
  public/locales/ml/gamepage.json
  public/locales/nl/gamepage.json
  public/locales/pl/gamepage.json
  public/locales/pt/gamepage.json
  public/locales/pt_BR/gamepage.json
  public/locales/ru/gamepage.json
  public/locales/sv/gamepage.json
  public/locales/ta/gamepage.json
  public/locales/tr/gamepage.json
  public/locales/uk/gamepage.json
  public/locales/vi/gamepage.json
  public/locales/zh_Hans/gamepage.json
  public/locales/zh_Hant/gamepage.json
  src/screens/Game/GamePage/index.css
  src/screens/Game/GamePage/index.tsx
  src/screens/Library/components/GameCard/index.tsx
  src/state/GlobalState.tsx
Labels: pr:ready-for-review

#1296 [Linux] Use Steam Runtime with Proton
  electron/gog/games.ts
  electron/launcher.ts
  electron/legendary/games.ts
  electron/types.ts
  electron/utils.ts
  flatpak/local.heroic.yml
  src/components/UI/SelectField/index.css
  src/screens/Settings/components/OtherSettings/index.tsx
  src/screens/Settings/index.tsx
Labels: pr:ready-for-review

#1359 Change Steam Runtime search path
  electron/utils.ts
Labels: pr:ready-for-review

#1362 Add new `--no-gui` parameter
  electron/main.ts
  electron/protocol.ts
Labels: pr:ready-for-review

#1358 Allow specifying wrappers in the env var section again
  electron/launcher.ts
Labels: pr:ready-to-merge

#1355 Set Steam App ID variables when using the Runtime on Proton + fixup setting user-defined env vars on native games
  electron/launcher.ts
  flatpak/local.heroic.yml
Labels: pr:ready-to-merge

#1369 [Linux] Search for Proton on all steam libraries
  electron/config.ts
  electron/constants.ts
  package.json
  yarn.lock
Labels: pr:ready-for-review

#1387 [Fix] Proper Check if a game is native or not
  electron/games.ts
  electron/gog/games.ts
  electron/legendary/games.ts
  src/screens/Library/index.tsx
Labels: pr:ready-for-review

#1388 Fixup verifyWinePrefix for Proton... again
  electron/launcher.ts
Labels: pr:ready-to-merge

#1392 Try to fix macOS not launching CX
  electron/launcher.ts
Labels: pr:wip, pr:testing

#1386 Always update Winetricks if we are online
  electron/tools.ts
Labels: pr:ready-to-merge

#1389 [UX] Use better paths on open dialog
  src/helpers/library.ts
  src/screens/Game/GameSubMenu/index.tsx
  src/screens/Library/components/InstallModal/index.tsx
  src/screens/Settings/components/GeneralSettings/index.tsx
  src/screens/Settings/components/OtherSettings/index.tsx
  src/screens/Settings/components/Tools/index.tsx
  src/screens/Settings/components/WineSettings/index.tsx
  src/screens/Settings/index.tsx
Labels: pr:ready-for-review

#1399 [macOS] Check for CX bottle existence before launching a game
  electron/launcher.ts
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
Labels: pr:ready-to-merge

#1394 [Fix] Styling and error Dialogs
  electron/config.ts
  electron/game_config.ts
  electron/gog/games.ts
  electron/launcher.ts
  electron/legendary/games.ts
  electron/shortcuts.ts
  src/App.css
  src/components/UI/SelectField/index.css
  src/screens/Settings/components/SyncSaves/index.tsx
  src/screens/Settings/components/Tools/index.tsx
  src/screens/Settings/components/WineSettings/index.tsx
  src/screens/Settings/index.css
Labels: pr:ready-for-review

#1384 Fixes relating to Proton & the Steam Runtime
  electron/launcher.ts
  electron/legendary/games.ts
  electron/main.ts
  electron/tools.ts
  electron/utils.ts
  src/screens/Settings/components/Tools/index.tsx
  src/screens/Settings/index.tsx
Labels: pr:ready-to-merge

#1402 [Fix] Sync saves not working on different languages than english
  src/screens/Settings/components/SyncSaves/index.tsx
Labels: pr:ready-for-review

#1411 [Fix] Library not showing and Corrupted config dialog
  electron/config.ts
  electron/game_config.ts
  electron/launcher.ts
  electron/legendary/library.ts
  electron/logger/logger.ts
  electron/main.ts
  electron/utils.ts
  package.json
  src/components/UI/Header/index.tsx
  src/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/screens/Library/constants.ts
  src/screens/Library/index.tsx
  src/screens/WebView/index.tsx
  src/state/ContextProvider.tsx
  src/state/GlobalState.tsx
  src/types.ts
Labels: pr:ready-for-review
