Repository Heroic-Games-Launcher/HeroicGamesLauncher, pull requests merged in 2022-11, with the labels that each got.

#1969 [General/Protocol] Fix protocol not launching gog games
  src/backend/protocol.ts
Labels: pr:ready-to-merge

#1887 [TECH] Move default save computation into the backend
  src/backend/api/helpers.ts
  src/backend/api/misc.ts
  src/backend/gog/library.ts
  src/backend/launcher.ts
  src/backend/legendary/library.ts
  src/backend/main.ts
  src/backend/save_sync.ts
  src/backend/utils.ts
  src/common/types.ts
  src/common/types/gog.ts
  src/frontend/helpers/index.ts
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
  src/frontend/screens/Settings/components/SyncSaves/gog.tsx
  src/frontend/screens/Settings/components/SyncSaves/legendary.tsx
Labels: pr:ready-for-review

#1987 [Fix] Verify that a valid Wine/Proton prefix exists before running any Wine command
  src/backend/launcher.ts
  src/backend/legendary/eos_overlay/eos_overlay.ts
  src/backend/main.ts
  src/common/types.ts
Labels: pr:ready-for-review

#1996 [UI] Fix dialog content width
  src/frontend/components/UI/DialogHandler/components/MessageBoxModal/index.css
  src/frontend/components/UI/ProgressDialog/index.css
Labels: pr:ready-for-review

#1994 [UI] Fixes game page scroll when content doesn't fit the screen
  src/frontend/screens/Game/GamePage/index.scss
Labels: pr:ready-for-review

#2007 [UI] Hide Clear button for Library's Search Bar
  src/frontend/components/UI/SearchBar/index.tsx
Labels: pr:ready-for-review

#2019 [Fix] Steam runtime making games fail to launch
  src/backend/gog/games.ts
  src/backend/launcher.ts
  src/backend/legendary/games.ts
  src/backend/sideload/games.ts
Labels: pr:ready-for-review

#2011 [Logs] Catch invalid JSON outputs from legendary when launching games
  src/backend/legendary/games.ts
Labels: pr:ready-for-review

#2008 [UI] Hide wine-related settings for games when Wine is not used
  src/frontend/screens/Settings/SettingsContext.tsx
  src/frontend/screens/Settings/components/EnableEsync.tsx
  src/frontend/screens/Settings/components/EnableFSR.tsx
  src/frontend/screens/Settings/components/EnableFsync.tsx
  src/frontend/screens/Settings/components/ShowFPS.tsx
  src/frontend/screens/Settings/components/SteamRuntime.tsx
  src/frontend/screens/Settings/index.tsx
  src/frontend/screens/Settings/sections/GamesSettings/index.tsx
  src/frontend/types.ts
Labels: pr:ready-for-review

#2022 [Linux - UI/UX] Show Checkbox to use default Wine Settings on new Installs
  public/locales/az/gamepage.json
  public/locales/be/gamepage.json
  public/locales/bg/gamepage.json
  public/locales/bs/gamepage.json
  public/locales/ca/gamepage.json
  public/locales/cs/gamepage.json
  public/locales/de/gamepage.json
  public/locales/el/gamepage.json
  public/locales/en/gamepage.json
  public/locales/es/gamepage.json
  public/locales/et/gamepage.json
  public/locales/eu/gamepage.json
  public/locales/fa/gamepage.json
  public/locales/fa/translation.json
  public/locales/fi/gamepage.json
  public/locales/fr/gamepage.json
  public/locales/fr/translation.json
  public/locales/gl/gamepage.json
  public/locales/hr/gamepage.json
  public/locales/hu/gamepage.json
  public/locales/id/gamepage.json
  public/locales/it/gamepage.json
  public/locales/ja/gamepage.json
  public/locales/ko/gamepage.json
  public/locales/ml/gamepage.json
  public/locales/nb_NO/gamepage.json
  public/locales/nl/gamepage.json
  public/locales/pl/gamepage.json
  public/locales/pt/gamepage.json
  public/locales/pt_BR/gamepage.json
  public/locales/ro/gamepage.json
  public/locales/ru/gamepage.json
  public/locales/sk/gamepage.json
  public/locales/sv/gamepage.json
  public/locales/ta/gamepage.json
  public/locales/tr/gamepage.json
  public/locales/uk/gamepage.json
  public/locales/vi/gamepage.json
  public/locales/zh_Hans/gamepage.json
  public/locales/zh_Hant/gamepage.json
  src/backend/config.ts
  src/frontend/components/UI/ToggleSwitch/index.tsx
  src/frontend/helpers/index.ts
  src/frontend/screens/Library/components/InstallModal/WineSelector/index.tsx
  src/frontend/screens/Library/components/InstallModal/index.tsx
  src/frontend/screens/Settings/components/WinePrefix.tsx
  src/frontend/screens/Settings/index.tsx
  src/frontend/state/GlobalState.tsx
Labels: pr:ready-for-review

#2037 `--offline` flag fix for beta
  src/backend/legendary/games.ts
Labels: pr:ready-for-review

#2038 [Fix/Epic] Handle metadata files with dots in their name correctly
  src/backend/legendary/library.ts
Labels: pr:ready-for-review

#2032 [UI] Show How Long to Beat Data on Game Page
  package.json
  public/locales/az/gamepage.json
  public/locales/be/gamepage.json
  public/locales/bg/gamepage.json
  public/locales/bs/gamepage.json
  public/locales/ca/gamepage.json
  public/locales/cs/gamepage.json
  public/locales/de/gamepage.json
  public/locales/el/gamepage.json
  public/locales/en/gamepage.json
  public/locales/es/gamepage.json
  public/locales/et/gamepage.json
  public/locales/eu/gamepage.json
  public/locales/fa/gamepage.json
  public/locales/fi/gamepage.json
  public/locales/fr/gamepage.json
  public/locales/gl/gamepage.json
  public/locales/hr/gamepage.json
  public/locales/hu/gamepage.json
  public/locales/id/gamepage.json
  public/locales/it/gamepage.json
  public/locales/ja/gamepage.json
  public/locales/ko/gamepage.json
  public/locales/ml/gamepage.json
  public/locales/nb_NO/gamepage.json
  public/locales/nl/gamepage.json
  public/locales/pl/gamepage.json
  public/locales/pt/gamepage.json
  public/locales/pt_BR/gamepage.json
  public/locales/ro/gamepage.json
  public/locales/ru/gamepage.json
  public/locales/sk/gamepage.json
  public/locales/sv/gamepage.json
  public/locales/ta/gamepage.json
  public/locales/tr/gamepage.json
  public/locales/uk/gamepage.json
  public/locales/vi/gamepage.json
  public/locales/zh_Hans/gamepage.json
  public/locales/zh_Hant/gamepage.json
  src/backend/api/misc.ts
  src/backend/howlongtobeat/ipc_handler.ts
  src/backend/howlongtobeat/utils.ts
  src/backend/main.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/components/UI/HowLongToBeat/index.scss
  src/frontend/components/UI/HowLongToBeat/index.tsx
  src/frontend/screens/Game/GamePage/index.tsx
  yarn.lock
Labels: pr:ready-for-review

#2042 Add a timeout when watching Legendary's `installed.json`
  src/backend/main.ts
Labels: pr:ready-for-review

#2004 Use new `--accept-path` flag in save sync
  src/backend/save_sync.ts
Labels: pr:ready-to-merge, pr:ready-for-review

#1988 [General] Avoid unnecessary config writes
  src/backend/api/helpers.ts
  src/common/typedefs/ipcBridge.d.ts
  src/common/types.ts
  src/frontend/hooks/useSetting.ts
  src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx
  src/frontend/screens/Settings/SettingsContext.tsx
  src/frontend/screens/Settings/index.tsx
  src/frontend/types.ts
Labels: pr:ready-to-merge, pr:ready-for-review

#2054 [Fix/Epic] Only delete `userInfo` key from configStore when logging out
  src/backend/legendary/user.ts
Labels: pr:ready-for-review

#2041 [UI] Small Improvements
  src/frontend/components/UI/CachedImage/index.tsx
  src/frontend/screens/Library/components/GameCard/index.tsx
  src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.scss
  src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx
  src/frontend/screens/Library/components/InstallModal/index.css
  src/frontend/screens/Settings/components/Tools/index.scss
  src/frontend/screens/Settings/index.css
  src/frontend/screens/Settings/sections/FooterInfo/index.tsx
Labels: pr:ready-for-review

#2083 [Tech] Cherry pick main commits into beta
  .github/ISSUE_TEMPLATE/bug_report.yaml
  README.md
  public/locales/ar/gamepage.json
  public/locales/ar/translation.json
  public/locales/cs/gamepage.json
  public/locales/cs/login.json
  public/locales/cs/translation.json
  public/locales/eu/gamepage.json
  public/locales/eu/translation.json
  public/locales/fa/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ta/gamepage.json
  src/frontend/components/UI/CachedImage/index.tsx
  src/frontend/helpers/gamepad.ts
  src/frontend/helpers/gamepad_layouts/index.ts
  src/frontend/helpers/gamepad_layouts/nintendo.ts
  src/frontend/helpers/gamepad_layouts/standard.ts
  src/frontend/screens/Library/components/LibraryHeader/index.tsx
  src/frontend/screens/Library/index.tsx
Labels: pr:ready-for-review
