Repository Heroic-Games-Launcher/HeroicGamesLauncher, pull requests merged in 2022-08, with the labels that each got.

#1656 [macOS - Fix] Find crossover issue + launch win games issue + Renamed Settings
  electron/config.ts
  electron/constants.ts
  electron/gog/games.ts
  electron/legendary/games.ts
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/screens/Settings/components/WineSettings/index.tsx
Labels: pr:ready-for-review

#1651 [Fix] Fix some bugs with the OSK
  src/helpers/virtualKeyboard.ts
  src/index.css
  src/themes.css
Labels: pr:ready-for-review

#1646 [Tech] Add Runner param to all routes
  .gitignore
  electron/legendary/eos_overlay/eos_overlay.ts
  electron/utils.ts
  src/App.tsx
  src/components/UI/Sidebar/components/CurrentDownload/index.tsx
  src/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/components/UI/Sidebar/index.tsx
  src/helpers/index.ts
  src/screens/Game/GamePage/index.css
  src/screens/Game/GamePage/index.tsx
  src/screens/Library/components/GameCard/index.tsx
  src/screens/Settings/components/OtherSettings/index.tsx
  src/screens/Settings/components/Tools/index.tsx
  src/screens/Settings/index.tsx
Labels: pr:ready-for-review

#1575 [Fix] Path not Writable + Disk Space Info
  electron/main.ts
  electron/utils.ts
  package.json
  src/components/UI/ControllerHints/index.tsx
  src/components/UI/Sidebar/components/SidebarLinks/index.tsx
  yarn.lock
Labels: pr:ready-for-review

#1662 [Fix] Show uncaught exception in frontend and exit heroic.
  electron/main.ts
  electron/utils.ts
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
Labels: pr:ready-to-merge

#1674 [UX] Alert the user about new Heroic updates for Stable and Beta Releases
  electron/__tests__/utils.test.ts
  electron/constants.ts
  electron/main.ts
  electron/types.ts
  electron/utils.ts
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/components/UI/Sidebar/components/HeroicVersion/index.tsx
  src/components/UI/Sidebar/index.css
  src/components/UI/Sidebar/index.tsx
  src/screens/Settings/components/GeneralSettings/index.tsx
  src/screens/Settings/index.tsx
Labels: pr:ready-for-review

#1650 [Tech] AppVeyor Configuration
  .github/workflows/draft-release-win.yml
  .gitignore
  appveyor.yml
  package.json
Labels: pr:ready-for-review

#1669 [General] Show quit button if controller is activated
  src/components/UI/ControllerHints/index.tsx
  src/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/state/ContextProvider.tsx
  src/state/GlobalState.tsx
  src/types.ts
Labels: pr:ready-for-review

#1647 Update Electron to 20.0.1
  package.json
  yarn.lock
Labels: pr:testing, pr:ready-for-review

#1685 [Fix] Hide Install when downloading a game
  src/screens/Library/components/GameCard/index.tsx
Labels: pr:ready-for-review

#1693 [Fix] Disable notifications if they are not supported. (E.g. Steamdeck Gamemode)
  electron/__tests__/shortcuts/nonesteamgame.test.ts
  electron/shortcuts/nonesteamgame/nonesteamgame.ts
  electron/utils.ts
Labels: pr:ready-for-review

#1668 [GOG] Fix errors when offline
  electron/gog/library.ts
  electron/gog/user.ts
Labels: pr:ready-to-merge, pr:ready-for-review

#1702 [UI/UX] Game Page Tools Reorganization
  public/locales/bg/gamepage.json
  public/locales/ca/gamepage.json
  public/locales/cs/gamepage.json
  public/locales/de/gamepage.json
  public/locales/el/gamepage.json
  public/locales/en/gamepage.json
  public/locales/es/gamepage.json
  public/locales/et/gamepage.json
  public/locales/fa/gamepage.json
  public/locales/fi/gamepage.json
  public/locales/fr/gamepage.json
  public/locales/gl/gamepage.json
  public/locales/hr/gamepage.json
  public/locales/hu/gamepage.json
  public/locales/id/gamepage.json
  public/locales/it/gamepage.json
  public/locales/ja/gamepage.json
  public/locales/ko/gamepage.json
  public/locales/ml/gamepage.json
  public/locales/nl/gamepage.json
  public/locales/pl/gamepage.json
  public/locales/pt/gamepage.json
  public/locales/pt_BR/gamepage.json
  public/locales/ru/gamepage.json
  public/locales/sv/gamepage.json
  public/locales/ta/gamepage.json
  public/locales/tr/gamepage.json
  public/locales/uk/gamepage.json
  public/locales/vi/gamepage.json
  public/locales/zh_Hans/gamepage.json
  public/locales/zh_Hant/gamepage.json
  src/screens/Game/GameSubMenu/index.tsx
Labels: pr:ready-for-review

#1734 [UI] Show Cloud Save unsupported status
  public/locales/bg/gamepage.json
  public/locales/ca/gamepage.json
  public/locales/cs/gamepage.json
  public/locales/de/gamepage.json
  public/locales/el/gamepage.json
  public/locales/en/gamepage.json
  public/locales/es/gamepage.json
  public/locales/et/gamepage.json
  public/locales/fa/gamepage.json
  public/locales/fi/gamepage.json
  public/locales/fr/gamepage.json
  public/locales/gl/gamepage.json
  public/locales/hr/gamepage.json
  public/locales/hu/gamepage.json
  public/locales/id/gamepage.json
  public/locales/it/gamepage.json
  public/locales/ja/gamepage.json
  public/locales/ko/gamepage.json
  public/locales/ml/gamepage.json
  public/locales/nl/gamepage.json
  public/locales/pl/gamepage.json
  public/locales/pt/gamepage.json
  public/locales/pt_BR/gamepage.json
  public/locales/ru/gamepage.json
  public/locales/sv/gamepage.json
  public/locales/ta/gamepage.json
  public/locales/tr/gamepage.json
  public/locales/uk/gamepage.json
  public/locales/vi/gamepage.json
  public/locales/zh_Hans/gamepage.json
  public/locales/zh_Hant/gamepage.json
  src/screens/Game/GamePage/index.tsx
Labels: pr:ready-for-review

#1725 Remove extra game status change when killing a game
  src/screens/Library/components/GameCard/index.tsx
Labels: pr:ready-for-review

#1720 Some UX improvements on env variables
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/components/UI/TwoColTableInput/index.css
  src/components/UI/TwoColTableInput/index.tsx
  src/screens/Settings/components/OtherSettings/EnvVariablesTable.tsx
  src/screens/Settings/components/OtherSettings/index.tsx
Labels: pr:ready-for-review

#1723 [Fix] Add winetricks dependencies for Flatpak
  flatpak/local.heroic.yml
  flatpak/patches/p7zip/gcc10-conversion.patch
Labels: pr:ready-for-review

#1751 [FIX] Don't show Recent Games if the list is empty
  src/screens/Library/components/RecentlyPlayed/index.tsx
Labels: pr:ready-for-review

#1730 [UI] Show winetricks progress output and Sync-Saves output via React Dialog
  electron/main.ts
  electron/tools.ts
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/components/UI/Dialog/components/DialogHeader.tsx
  src/components/UI/ProgressDialog/index.css
  src/components/UI/ProgressDialog/index.tsx
  src/screens/Library/components/InstallModal/index.tsx
  src/screens/Settings/components/SyncSaves/gog.tsx
  src/screens/Settings/components/SyncSaves/legendary.tsx
  src/screens/Settings/components/Tools/index.tsx
Labels: pr:ready-for-review
