Repository Heroic-Games-Launcher/HeroicGamesLauncher, pull requests merged in 2022-10, with the labels that each got.

#1862 [Fix] Game status not updating on uninstall
  src/frontend/components/UI/CachedImage/index.tsx
  src/frontend/screens/Game/GamePage/index.tsx
Labels: pr:ready-for-review

#1876 Fix setting not updating after another setting changes
  src/frontend/hooks/useSetting.ts
Labels: pr:ready-for-review

#1841 Move `Tools` content into a menu
  public/locales/az/gamepage.json
  public/locales/be/gamepage.json
  public/locales/bg/gamepage.json
  public/locales/bs/gamepage.json
  public/locales/ca/gamepage.json
  public/locales/cs/gamepage.json
  public/locales/de/gamepage.json
  public/locales/el/gamepage.json
  public/locales/en/gamepage.json
  public/locales/es/gamepage.json
  public/locales/et/gamepage.json
  public/locales/eu/gamepage.json
  public/locales/fa/gamepage.json
  public/locales/fi/gamepage.json
  public/locales/fr/gamepage.json
  public/locales/gl/gamepage.json
  public/locales/hr/gamepage.json
  public/locales/hu/gamepage.json
  public/locales/id/gamepage.json
  public/locales/it/gamepage.json
  public/locales/ja/gamepage.json
  public/locales/ko/gamepage.json
  public/locales/ml/gamepage.json
  public/locales/nb_NO/gamepage.json
  public/locales/nl/gamepage.json
  public/locales/pl/gamepage.json
  public/locales/pt/gamepage.json
  public/locales/pt_BR/gamepage.json
  public/locales/ro/gamepage.json
  public/locales/ru/gamepage.json
  public/locales/sk/gamepage.json
  public/locales/sv/gamepage.json
  public/locales/ta/gamepage.json
  public/locales/tr/gamepage.json
  public/locales/uk/gamepage.json
  public/locales/vi/gamepage.json
  public/locales/zh_Hans/gamepage.json
  public/locales/zh_Hant/gamepage.json
  src/frontend/components/UI/SmallInfo/index.tsx
  src/frontend/screens/Game/GamePage/index.css
  src/frontend/screens/Game/GamePage/index.scss
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Game/GameSubMenu/index.tsx
Labels: pr:ready-for-review

#1882 [UI] Tweak backToTopBtn color theme
  src/frontend/screens/Library/index.css
Labels: pr:ready-for-review

#1852 [Linux] Set some more Wine-related env vars when launching with built-in libraries
  src/backend/launcher.ts
Labels: pr:ready-for-review

#1873 [Fix] Unicode chars in non-steam-game error dialog
  src/backend/shortcuts/nonesteamgame/nonesteamgame.ts
Labels: pr:ready-for-review

#1899 Move game menu next to the title
  src/frontend/screens/Game/GamePage/index.scss
  src/frontend/screens/Game/GamePage/index.tsx
Labels: pr:ready-for-review

#1894 [Linux] Fixup: Show Wine Prefix in Game Settings again
  src/frontend/screens/Settings/components/WineSettings/WinePrefix.tsx
Labels: pr:ready-for-review

#1895 [Tech] Make it possible to disable the React developer tools
  README.md
  src/backend/main.ts
Labels: pr:ready-for-review

#1916 Do not check the EOS overlay for GOG games
  src/frontend/screens/Game/GameSubMenu/index.tsx
Labels: pr:ready-for-review

#1912 Show an error if the select wine doesn't exist
  public/locales/az/translation.json
  public/locales/be/translation.json
  public/locales/bg/translation.json
  public/locales/bs/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/eu/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nb_NO/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ro/translation.json
  public/locales/ru/translation.json
  public/locales/sk/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/backend/gog/games.ts
  src/backend/launcher.ts
  src/backend/legendary/games.ts
  src/backend/tools.ts
Labels: pr:ready-for-review

#1907 Remove `draggable` from `Run EXE on Prefix` button
  src/frontend/screens/Settings/components/Tools/index.tsx
Labels: pr:ready-for-review

#1903 Fix automatic shortcuts creation
  src/backend/gog/games.ts
  src/backend/legendary/games.ts
Labels: pr:ready-for-review

#1897 [Tech] System info cache
  src/backend/main.ts
  src/backend/utils.ts
Labels: pr:ready-for-review

#1902 Fix error when clicking "Settings" when the current screen is a login webview
  src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
Labels: pr:ready-to-merge, pr:ready-for-review

#1904 Add shortcuts to Steam automatically
  public/locales/az/translation.json
  public/locales/be/translation.json
  public/locales/bg/translation.json
  public/locales/bs/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/eu/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nb_NO/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ro/translation.json
  public/locales/ru/translation.json
  public/locales/sk/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/backend/api/menu.ts
  src/backend/config.ts
  src/backend/gog/games.ts
  src/backend/legendary/games.ts
  src/backend/shortcuts/ipc_handler.ts
  src/backend/shortcuts/nonesteamgame/nonesteamgame.ts
  src/backend/shortcuts/shortcuts/shortcuts.ts
  src/common/types.ts
  src/frontend/index.tsx
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Game/GameSubMenu/index.tsx
  src/frontend/screens/Settings/components/OtherSettings/Shortcuts.tsx
  src/frontend/types.ts
Labels: pr:ready-for-review

#1921 [Linux] Remove Resizable BAR toggle
  src/backend/game_config.ts
  src/backend/launcher.ts
  src/common/types.ts
  src/frontend/screens/Settings/components/WineSettings/ResizableBar.tsx
  src/frontend/screens/Settings/components/WineSettings/index.tsx
Labels: pr:ready-for-review

#1919 [Fix] Pass `--offline` correctly again
  src/backend/legendary/games.ts
Labels: pr:ready-for-review

#1376 [UI] Update login with new designs
  public/locales/az/translation.json
  public/locales/be/translation.json
  public/locales/bg/translation.json
  public/locales/bs/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/eu/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nb_NO/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ro/translation.json
  public/locales/ru/translation.json
  public/locales/sk/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/frontend/assets/heroic-icon.svg
  src/frontend/screens/Login/components/Runner/index.css
  src/frontend/screens/Login/components/Runner/index.tsx
  src/frontend/screens/Login/index.css
  src/frontend/screens/Login/index.tsx
Labels: pr:testing

#1933 Some dialog fixes
  src/frontend/components/UI/Dialog/components/Dialog.tsx
  src/frontend/components/UI/Dialog/index.css
  src/frontend/screens/Library/components/GameCard/index.tsx
Labels: pr:ready-for-review

#1900 Try to prevent login using the store webview
  public/locales/az/gamepage.json
  public/locales/be/gamepage.json
  public/locales/bg/gamepage.json
  public/locales/bs/gamepage.json
  public/locales/ca/gamepage.json
  public/locales/cs/gamepage.json
  public/locales/de/gamepage.json
  public/locales/el/gamepage.json
  public/locales/en/gamepage.json
  public/locales/es/gamepage.json
  public/locales/et/gamepage.json
  public/locales/eu/gamepage.json
  public/locales/fa/gamepage.json
  public/locales/fi/gamepage.json
  public/locales/fr/gamepage.json
  public/locales/gl/gamepage.json
  public/locales/hr/gamepage.json
  public/locales/hu/gamepage.json
  public/locales/id/gamepage.json
  public/locales/it/gamepage.json
  public/locales/ja/gamepage.json
  public/locales/ko/gamepage.json
  public/locales/ml/gamepage.json
  public/locales/nb_NO/gamepage.json
  public/locales/nl/gamepage.json
  public/locales/pl/gamepage.json
  public/locales/pt/gamepage.json
  public/locales/pt_BR/gamepage.json
  public/locales/ro/gamepage.json
  public/locales/ru/gamepage.json
  public/locales/sk/gamepage.json
  public/locales/sv/gamepage.json
  public/locales/ta/gamepage.json
  public/locales/tr/gamepage.json
  public/locales/uk/gamepage.json
  public/locales/vi/gamepage.json
  public/locales/zh_Hans/gamepage.json
  public/locales/zh_Hant/gamepage.json
  src/frontend/screens/Login/components/LoginWarning/index.scss
  src/frontend/screens/Login/components/LoginWarning/index.tsx
  src/frontend/screens/Login/index.tsx
  src/frontend/screens/WebView/index.css
  src/frontend/screens/WebView/index.tsx
Labels: pr:ready-for-review

#1939 Allow using custom CSS files to theme Heroic
  public/locales/az/translation.json
  public/locales/be/translation.json
  public/locales/bg/translation.json
  public/locales/bs/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/eu/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nb_NO/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ro/translation.json
  public/locales/ru/translation.json
  public/locales/sk/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/backend/api/helpers.ts
  src/backend/constants.ts
  src/backend/main.ts
  src/common/types.ts
  src/frontend/components/UI/InfoBox/index.tsx
  src/frontend/components/UI/TextInputField/index.tsx
  src/frontend/components/UI/TextInputWithIconField/index.tsx
  src/frontend/components/UI/ThemeSelector/index.tsx
  src/frontend/helpers/index.ts
  src/frontend/index.tsx
  src/frontend/state/GlobalState.tsx
  src/frontend/types.ts
Labels: pr:ready-for-review

#1937 [Feature] Allow removing elements from recently played
  public/locales/az/gamepage.json
  public/locales/be/gamepage.json
  public/locales/bg/gamepage.json
  public/locales/bs/gamepage.json
  public/locales/ca/gamepage.json
  public/locales/cs/gamepage.json
  public/locales/de/gamepage.json
  public/locales/el/gamepage.json
  public/locales/en/gamepage.json
  public/locales/es/gamepage.json
  public/locales/et/gamepage.json
  public/locales/eu/gamepage.json
  public/locales/fa/gamepage.json
  public/locales/fi/gamepage.json
  public/locales/fr/gamepage.json
  public/locales/gl/gamepage.json
  public/locales/hr/gamepage.json
  public/locales/hu/gamepage.json
  public/locales/id/gamepage.json
  public/locales/it/gamepage.json
  public/locales/ja/gamepage.json
  public/locales/ko/gamepage.json
  public/locales/ml/gamepage.json
  public/locales/nb_NO/gamepage.json
  public/locales/nl/gamepage.json
  public/locales/pl/gamepage.json
  public/locales/pt/gamepage.json
  public/locales/pt_BR/gamepage.json
  public/locales/ro/gamepage.json
  public/locales/ru/gamepage.json
  public/locales/sk/gamepage.json
  public/locales/sv/gamepage.json
  public/locales/ta/gamepage.json
  public/locales/tr/gamepage.json
  public/locales/uk/gamepage.json
  public/locales/vi/gamepage.json
  public/locales/zh_Hans/gamepage.json
  public/locales/zh_Hant/gamepage.json
  src/backend/api/library.ts
  src/backend/main.ts
  src/backend/recent_games.ts
  src/common/types.ts
  src/frontend/helpers/library.ts
  src/frontend/screens/Library/components/GameCard/index.tsx
  src/frontend/screens/Library/components/GamesList/index.tsx
  src/frontend/screens/Library/components/RecentlyPlayed/index.tsx
Labels: pr:wip

#1952 [UI] Refactor Action Icons
  src/frontend/components/UI/FormControl/index.css
  src/frontend/styles/_colors.scss
  src/frontend/themes.css
Labels: pr:ready-for-review

#1953 Optimize eslint settings
  package.json
  tsconfig.json
Labels: pr:ready-for-review

#1950 Fix some issues when uninstalling games
  public/locales/az/gamepage.json
  public/locales/be/gamepage.json
  public/locales/bg/gamepage.json
  public/locales/bs/gamepage.json
  public/locales/ca/gamepage.json
  public/locales/cs/gamepage.json
  public/locales/de/gamepage.json
  public/locales/el/gamepage.json
  public/locales/en/gamepage.json
  public/locales/es/gamepage.json
  public/locales/et/gamepage.json
  public/locales/eu/gamepage.json
  public/locales/fa/gamepage.json
  public/locales/fi/gamepage.json
  public/locales/fr/gamepage.json
  public/locales/gl/gamepage.json
  public/locales/hr/gamepage.json
  public/locales/hu/gamepage.json
  public/locales/id/gamepage.json
  public/locales/it/gamepage.json
  public/locales/ja/gamepage.json
  public/locales/ko/gamepage.json
  public/locales/ml/gamepage.json
  public/locales/nb_NO/gamepage.json
  public/locales/nl/gamepage.json
  public/locales/pl/gamepage.json
  public/locales/pt/gamepage.json
  public/locales/pt_BR/gamepage.json
  public/locales/ro/gamepage.json
  public/locales/ru/gamepage.json
  public/locales/sk/gamepage.json
  public/locales/sv/gamepage.json
  public/locales/ta/gamepage.json
  public/locales/tr/gamepage.json
  public/locales/uk/gamepage.json
  public/locales/vi/gamepage.json
  public/locales/zh_Hans/gamepage.json
  public/locales/zh_Hant/gamepage.json
  src/backend/api/library.ts
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Library/components/GameCard/index.tsx
Labels: pr:ready-for-review

#1958 [MacOS/Linux] Fix up runWineCommand
  src/backend/api/helpers.ts
  src/backend/games.ts
  src/backend/gog/games.ts
  src/backend/launcher.ts
  src/backend/legendary/games.ts
  src/backend/main.ts
  src/backend/sideload/games.ts
  src/common/types.ts
  src/frontend/helpers/index.ts
  src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx
  src/frontend/screens/Settings/components/SyncSaves/gog.tsx
  src/frontend/screens/Settings/components/SyncSaves/legendary.tsx
Labels: pr:ready-for-review
