Repository Heroic-Games-Launcher/HeroicGamesLauncher, pull requests merged in 2022-06, with the labels that each got.

#1448 Fix toggle switch ids in install dialog
  src/screens/Library/components/InstallModal/index.tsx
Labels: pr:ready-for-review

#1438 Disable controller on boot
  src/helpers/gamepad.ts
Labels: pr:ready-for-review

#1440 Change Game Language
  electron/legendary/games.ts
  electron/types.ts
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/components/UI/LanguageSelector/index.tsx
  src/index.tsx
  src/screens/Settings/components/OtherSettings/index.tsx
  src/screens/Settings/index.tsx
  src/types.ts
Labels: pr:ready-for-review

#1450 Fix detection of search bar focus to open virtual keyboard
  src/components/UI/SearchBar/index.tsx
  src/helpers/gamepad.ts
Labels: pr:ready-for-review

#1443 Pass SDL list as multiple arguments
  electron/legendary/games.ts
Labels: pr:ready-to-merge

#1409 [Linux] Added option to display Wine executable path
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/screens/Settings/components/WineSettings/index.tsx
Labels: enhancement, pr:ready-for-review

#1442 [General] Fix: No longer replace token/sid with redacted
  electron/launcher.ts
Labels: pr:ready-to-merge

#1464 [Fix] multiple settings writes
  electron/main.ts
  src/screens/Settings/components/AdvancedSettings/index.tsx
  src/screens/Settings/index.tsx
Labels: pr:ready-for-review

#1501 Refactor/fix: Wait until frontend is ready before processing protocol/args
  electron/main.ts
  electron/protocol.ts
  src/state/GlobalState.tsx
Labels: pr:ready-for-review

#1481 [Epic] Fix: Pass empty SDL tag properly
  electron/legendary/games.ts
Labels: pr:ready-for-review

#1520 [General] Add launcherArgs to native games again
  electron/legendary/games.ts
Labels: pr:ready-for-review
