Repository Heroic-Games-Launcher/HeroicGamesLauncher, pull requests merged in 2022-01, with the labels that each got.

#869 [General] Refactor and enable spatial navigation
  electron/main.ts
  src/App.tsx
  src/components/UI/Header/index.css
  src/components/UI/SvgButton/index.tsx
  src/screens/Library/components/GameCard/index.css
  src/screens/Library/components/GameCard/index.tsx
  src/screens/Library/components/InstallModal/index.css
  src/screens/Library/index.css
  src/screens/Library/index.tsx
Labels: pr:ready-for-review

#824 Replace electron-is-dev with built-in electron constant "isPackaged"
  electron/main.ts
  package.json
Labels: pr:ready-for-review

#889 Show the switch focus outline only with keyboard, not mouse
  src/components/UI/ToggleSwitch/index.css
Labels: pr:ready-to-merge

#880 Support nagivating Heroic using a gamepad
  electron/main.ts
  electron/types.ts
  package.json
  public/index.html
  src/components/UI/SearchBar/index.tsx
  src/helpers/gamepad.ts
  src/helpers/virtualKeyboard.ts
  src/index.css
  src/index.tsx
  src/screens/Library/components/GameCard/index.tsx
  src/types.ts
  yarn.lock
Labels: pr:ready-for-review

#894 Support Ctrl+F and CMD+F shortcut to focus search bar
  src/helpers/shortcuts.ts
  src/index.tsx
Labels: pr:ready-for-review

#892 [Fix] DLCs list on Install Dialog
  src/screens/Game/GamePage/index.tsx
  src/screens/Library/components/InstallModal/index.css
  src/screens/Library/components/InstallModal/index.tsx
Labels: pr:ready-for-review

#911 Add prefix parameter for logger
  electron/__tests__/logger.test.ts
  electron/dxvk.ts
  electron/legendary/games.ts
  electron/logger.ts
  electron/main.ts
  electron/protocol.ts
Labels: pr:ready-for-review

#908 [General] Check epic status and show warning messages
  electron/legendary/games.ts
  electron/legendary/library.ts
  electron/legendary/user.ts
  electron/main.ts
  electron/utils.ts
  package.json
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/screens/WebView/index.tsx
  yarn.lock
Labels: pr:ready-for-review

#916 LogFile generation and log output improvment
  electron/__tests__/logger.test.ts
  electron/config.ts
  electron/constants.ts
  electron/dxvk.ts
  electron/game_config.ts
  electron/games.ts
  electron/legendary/games.ts
  electron/legendary/library.ts
  electron/legendary/user.ts
  electron/logger.ts
  electron/main.ts
  electron/protocol.ts
  electron/utils.ts
  src/screens/Login/index.tsx
Labels: pr:ready-for-review

#909 Refactor gamepads layotus and add some more
  src/helpers/gamepad.ts
  src/helpers/gamepad_layouts/genius.ts
  src/helpers/gamepad_layouts/index.ts
  src/helpers/gamepad_layouts/nintendo.ts
  src/helpers/gamepad_layouts/ps.ts
  src/helpers/gamepad_layouts/xbox.ts
Labels: pr:ready-for-review

#917 [General] Remember Window Size
  electron/main.ts
Labels: pr:ready-for-review

#925 [Bugfix] Removed python check.
  electron/main.ts
  electron/utils.ts
Labels: pr:ready-for-review

#932 [Bugfix] Fixed epic service status check.
  electron/dxvk.ts
  electron/legendary/games.ts
  electron/legendary/library.ts
  electron/legendary/user.ts
  electron/main.ts
  electron/utils.ts
  electron/wine-downloader/utils.ts
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
Labels: bug:confirmed, pr:ready-for-review, high priority

#939 [General] Add timestamp and relined logs
  electron/__tests__/logger.test.ts
  electron/legendary/library.ts
  electron/logger/logger.ts
Labels: pr:ready-for-review
