Repository Heroic-Games-Launcher/HeroicGamesLauncher, pull requests merged in 2022-12, with the labels that each got.

#2114 [GOG] Retry GOG install info if invalid language
  src/backend/gog/library.ts
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
Labels: pr:ready-for-review

#2113 [Connectivity] Connectivity check tweaks: ignore button, more ways to check, longer timeout
  public/locales/az/translation.json
  public/locales/be/translation.json
  public/locales/bg/translation.json
  public/locales/bs/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/eu/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/gamepage.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nb_NO/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ro/translation.json
  public/locales/ru/translation.json
  public/locales/sk/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/backend/api/helpers.ts
  src/backend/online_monitor.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/components/UI/OfflineMessage/index.css
  src/frontend/components/UI/OfflineMessage/index.scss
  src/frontend/components/UI/OfflineMessage/index.tsx
  src/frontend/screens/WebView/index.tsx
Labels: pr:ready-for-review

#2120 [Library] Disable Play button while launching game
  src/frontend/screens/Library/components/GameCard/index.css
  src/frontend/screens/Library/components/GameCard/index.tsx
Labels: pr:ready-for-review

#2068 [Feature/Wine] Add DXVK Framerate Limit Toggle
  public/locales/az/translation.json
  public/locales/be/translation.json
  public/locales/bg/translation.json
  public/locales/bs/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/eu/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nb_NO/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ro/translation.json
  public/locales/ru/translation.json
  public/locales/sk/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/backend/launcher.ts
  src/common/types.ts
  src/frontend/screens/Settings/components/EnableDXVKFpsLimit.tsx
  src/frontend/screens/Settings/components/index.ts
  src/frontend/screens/Settings/sections/GamesSettings/index.tsx
Labels: pr:ready-for-review

#2137 [Fix] Save sync for native games
  src/backend/legendary/library.ts
  src/backend/save_sync.ts
  src/common/types.ts
  src/common/types/legendary.ts
Labels: pr:ready-for-review

#2157 fix: pass skip-version-check only for legendary
  src/backend/legendary/games.ts
  src/backend/main.ts
Labels: pr:ready-to-merge

#2165 [FIX] Crossover not found on macOS
  src/backend/config.ts
Labels: pr:ready-for-review

#2171 [Legendary] Handle cases where CustomAttributes is undefined when getting cloud saved folder
  src/backend/legendary/library.ts
  src/common/types/legendary.ts
Labels: pr:ready-for-review

#2182 Theme selector in general settings
  src/frontend/screens/Settings/sections/GeneralSettings/index.tsx
Labels: pr:ready-for-review

#2172 Update github workflows for 'stable' branch
  .github/workflows/build-prs-linux.yml
  .github/workflows/build-prs-mac.yml
  .github/workflows/build-prs-windows.yml
  .github/workflows/build.yml
  .github/workflows/codecheck.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: pr:ready-for-review

#2180 [UI/UX] Cache HowLongtoBeat Data and move squares down
  src/backend/howlongtobeat/electronStores.ts
  src/backend/howlongtobeat/utils.ts
  src/backend/utils.ts
  src/frontend/components/UI/HowLongToBeat/index.tsx
  src/frontend/screens/Game/GamePage/index.tsx
Labels: pr:ready-for-review

#2184 [UI] Update Tray icon when recent games change
  package.json
  src/backend/__mocks__/config.ts
  src/backend/__mocks__/electron.ts
  src/backend/__mocks__/i18next.ts
  src/backend/backend_events.ts
  src/backend/main.ts
  src/backend/recent_games/__mocks__/recent_games.ts
  src/backend/recent_games/ipc_handler.ts
  src/backend/recent_games/recent_games.ts
  src/backend/tray_icon/__tests__/tray_icon.test.ts
  src/backend/tray_icon/tray_icon.ts
Labels: pr:ready-for-review

#2166 [Fix] DXVK + Winetricks on macOS
  package.json
  src/backend/config.ts
  src/backend/tools.ts
Labels: pr:ready-for-review

#2206 github: add discord link on new issue page
  .github/ISSUE_TEMPLATE/config.yaml
Labels: pr:ready-for-review

#2221 [WineManager] Fix status update
  src/frontend/screens/WineManager/index.tsx
Labels: pr:ready-for-review

#2191 [macOS] Add arm64 build
  .github/workflows/build-prs-linux.yml
  .github/workflows/build-prs-mac.yml
  .github/workflows/build-prs-windows.yml
  .github/workflows/build.yml
  .github/workflows/codecheck.yml
  .github/workflows/draft-release-linux.yml
  .github/workflows/draft-release-mac.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  package.json
  yarn.lock
Labels: pr:ready-for-review

#2215 [Tray Icon] Limit recent games on update
  src/backend/recent_games/__mocks__/recent_games.ts
  src/backend/recent_games/recent_games.ts
  src/backend/tray_icon/__tests__/tray_icon.test.ts
  src/backend/tray_icon/tray_icon.ts
Labels: pr:ready-for-review

#2216 [UI] Remove 'active' color from library icons
  src/frontend/components/UI/ActionIcons/index.tsx
Labels: pr:ready-for-review

#2200 [Refactor] Main window creating and send message to the frontend
  src/backend/__mocks__/electron.ts
  src/backend/__tests__/main_window.test.ts
  src/backend/dialog/dialog.ts
  src/backend/downloadmanager/downloadqueue.ts
  src/backend/downloadmanager/utils.ts
  src/backend/games.ts
  src/backend/gog/games.ts
  src/backend/legendary/games.ts
  src/backend/main.ts
  src/backend/main_window.ts
  src/backend/online_monitor.ts
  src/backend/protocol.ts
  src/backend/recent_games/recent_games.ts
  src/backend/shortcuts/nonesteamgame/nonesteamgame.ts
  src/backend/tray_icon/tray_icon.ts
  src/backend/utils.ts
  src/backend/wine/manager/ipc_handler.ts
  src/backend/wine/manager/utils.ts
Labels: pr:ready-for-review

#2208 [Refactor] Fix error with too many event listeners for the same progress update event
  src/backend/api/library.ts
  src/backend/downloadmanager/downloadqueue.ts
  src/backend/downloadmanager/utils.ts
  src/backend/gog/games.ts
  src/backend/legendary/games.ts
  src/backend/main.ts
  src/frontend/hooks/hasProgress.ts
  src/frontend/state/GlobalState.tsx
Labels: pr:ready-for-review

#2217 Indicate latest heroic version in bug report template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: pr:ready-for-review

#2203 [Fix] GOG games Setup on Windows
  src/backend/gog/games.ts
  src/backend/gog/setup.ts
  src/backend/utils.ts
Labels: pr:ready-for-review

#2241 [UI] Fix autoComplete list box position
  src/frontend/components/UI/SearchBar/index.css
Labels: pr:ready-to-merge

#2229 [Fix] Get store links for Epic from API response
  src/backend/gog/games.ts
  src/backend/gog/library.ts
  src/backend/legendary/games.ts
  src/backend/legendary/library.ts
  src/common/types.ts
  src/common/types/epic-graphql.ts
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Game/GameRequirements/index.tsx
Labels: pr:ready-for-review

#2224 [UI] Prevent flash when opening an installation dialog for the first time
  src/frontend/screens/Library/index.tsx
Labels: pr:ready-for-review

#2228 Extra info tweaks and improvements
  src/backend/api/helpers.ts
  src/backend/gog/games.ts
  src/backend/gog/library.ts
  src/backend/legendary/games.ts
  src/backend/legendary/library.ts
  src/backend/main.ts
  src/common/typedefs/ipcBridge.d.ts
  src/common/types.ts
  src/common/types/epic-graphql.ts
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Game/GameRequirements/index.tsx
Labels: pr:ready-for-review

#2248 Alternative Login visibility fixes
  src/frontend/themes.css
Labels: pr:ready-for-review

#2254 Remove `lastPlay` log when uninstalling a game
  src/backend/main.ts
Labels: pr:ready-for-review

#2267 [Download Manager] Some images fixes
  src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.css
  src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.tsx
  src/frontend/screens/DownloadManager/index.tsx
Labels: pr:ready-for-review

#2262 Prevent default settings env variables corruption
  src/backend/game_config.ts
Labels: pr:ready-for-review

#2260 Ignore remove from steam notification only if no errors
  src/backend/shortcuts/nonesteamgame/nonesteamgame.ts
Labels: pr:ready-for-review

#2261 Stop logging all controller interactions
  src/frontend/helpers/gamepad.ts
Labels: pr:ready-for-review

#2257 [FIX] Game status detection when uninstalling/running games
  src/frontend/components/UI/UninstallModal/index.tsx
  src/frontend/screens/Library/components/GameCard/index.tsx
  src/frontend/state/GlobalState.tsx
Labels: pr:ready-for-review

#2227 [UI/UX] Added warning dialog for external links
  src/frontend/App.tsx
  src/frontend/components/UI/ExternalLinkDialog/index.tsx
  src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/frontend/state/ContextProvider.tsx
  src/frontend/state/GlobalState.tsx
  src/frontend/types.ts
Labels: pr:testing, pr:ready-for-review

#2265 [Refactor] Load settings synchronously
  src/backend/__mocks__/config.ts
  src/backend/config.ts
  src/backend/constants.ts
  src/backend/game_config.ts
  src/backend/gog/games.ts
  src/backend/gog/setup.ts
  src/backend/launcher.ts
  src/backend/legendary/games.ts
  src/backend/legendary/user.ts
  src/backend/main.ts
  src/backend/recent_games/recent_games.ts
  src/backend/shortcuts/nonesteamgame/nonesteamgame.ts
  src/backend/shortcuts/shortcuts/shortcuts.ts
  src/backend/tray_icon/__tests__/tray_icon.test.ts
  src/backend/tray_icon/tray_icon.ts
Labels: pr:ready-for-review

#2264 [Refactor] Push status updates from the backend to the frontend
  src/backend/legendary/eos_overlay/eos_overlay.ts
  src/backend/main.ts
  src/backend/sideload/games.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/components/UI/UninstallModal/index.tsx
  src/frontend/screens/Game/GameSubMenu/index.tsx
  src/frontend/screens/Library/components/GameCard/index.tsx
  src/frontend/screens/Settings/sections/AdvancedSettings/index.tsx
  src/frontend/state/ContextProvider.tsx
  src/frontend/state/GlobalState.tsx
  src/frontend/types.ts
Labels: pr:ready-for-review

#2271 [Tech] Only parse english on `yarn i18n`
  i18next-parser.config.js
  src/backend/main.ts
  src/frontend/index.tsx
Labels: pr:ready-for-review

#2189 [Tech] Make it possible to specify only `prefix` when logging messages
  src/backend/anticheat/utils.ts
  src/backend/config.ts
  src/backend/constants.ts
  src/backend/dialog/dialog.ts
  src/backend/downloadmanager/downloadqueue.ts
  src/backend/downloadmanager/utils.ts
  src/backend/game_config.ts
  src/backend/gog/games.ts
  src/backend/gog/library.ts
  src/backend/gog/setup.ts
  src/backend/gog/user.ts
  src/backend/howlongtobeat/utils.ts
  src/backend/launcher.ts
  src/backend/legendary/eos_overlay/eos_overlay.ts
  src/backend/legendary/games.ts
  src/backend/legendary/library.ts
  src/backend/legendary/user.ts
  src/backend/logger/__tests__/logger.test.ts
  src/backend/logger/logger.ts
  src/backend/main.ts
  src/backend/online_monitor.ts
  src/backend/protocol.ts
  src/backend/save_sync.ts
  src/backend/shortcuts/nonesteamgame/nonesteamgame.ts
  src/backend/shortcuts/nonesteamgame/steamhelper.ts
  src/backend/shortcuts/shortcuts/shortcuts.ts
  src/backend/sideload/games.ts
  src/backend/tools.ts
  src/backend/tray_icon/tray_icon.ts
  src/backend/updater.ts
  src/backend/utils.ts
  src/backend/utils/aborthandler/aborthandler.ts
  src/backend/wine/manager/ipc_handler.ts
  src/backend/wine/manager/utils.ts
  src/backend/wine/runtimes/runtimes.ts
Labels: pr:ready-for-review

#2287 [UX] Open the game page from the card's context menu
  public/locales/en/gamepage.json
  src/frontend/screens/Library/components/GameCard/index.tsx
Labels: pr:ready-for-review
