Repository Heroic-Games-Launcher/HeroicGamesLauncher, pull requests merged in 2022-07, with the labels that each got.

#1529 [Fix] "default not writable"/"Path might not be writable" error
  src/screens/Library/components/InstallModal/index.tsx
Labels: pr:ready-for-review

#1548 [General] Logging & launching improvements
  electron/games.ts
  electron/gog/games.ts
  electron/launcher.ts
  electron/legendary/games.ts
  electron/main.ts
  electron/protocol.ts
  electron/shortcuts.ts
  electron/tools.ts
  electron/types.ts
  electron/utils.ts
  src/helpers/library.ts
Labels: pr:ready-for-review

#1522 [Steam-Deck] Always maximize Heroic if Steam-Deck gamemode
  electron/constants.ts
  electron/main.ts
  src/components/UI/Sidebar/components/SidebarLinks/index.tsx
Labels: pr:ready-for-review

#1504 [Linux] Add anticheat information when possible
  electron/anticheat/ipc_handler.ts
  electron/anticheat/utils.ts
  electron/constants.ts
  electron/main.ts
  electron/types.ts
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/components/UI/Anticheat/index.css
  src/components/UI/Anticheat/index.tsx
  src/index.css
  src/screens/Game/GamePage/index.tsx
  src/screens/Library/components/InstallModal/index.tsx
  src/types.ts
Labels: pr:ready-for-review

#1564 [Linux] Added option to prefer system libs
  electron/config.ts
  electron/game_config.ts
  electron/launcher.ts
  electron/types.ts
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/screens/Settings/components/WineSettings/index.tsx
  src/screens/Settings/index.tsx
  src/types.ts
Labels: pr:ready-to-merge, pr:ready-for-review

#1572 Some UI fixes for long strings on translations
  src/components/UI/Header/index.css
  src/components/UI/Sidebar/index.css
  src/components/UI/ToggleSwitch/index.css
  src/screens/Settings/index.css
Labels: pr:ready-to-merge

#1517 [UI] Fix Other Help Icon Boxes
  public/locales/en/translation.json
  src/screens/Settings/components/OtherSettings/index.tsx
Labels: pr:ready-for-review

#1514 [FIX] Remove ZSTD need for VKD3D
  electron/tools.ts
  package.json
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
Labels: pr:ready-for-review

#1566 [Fix] Not Checking games update on all platforms on refresh
  src/screens/Settings/components/GeneralSettings/index.tsx
  src/state/GlobalState.tsx
Labels: pr:ready-for-review

#1492 [Tech] Refactor game settings with fallbacks
  electron/game_config.ts
Labels: pr:wip, pr:ready-for-review

#1579 [UI] Sidebar settings button opens game settings on GamePage
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/components/UI/Sidebar/components/CurrentDownload/index.tsx
  src/components/UI/Sidebar/components/SidebarLinks/index.tsx
Labels: pr:ready-to-merge

#1582 [Fix] vkd3d and dxvk tar commands
  electron/tools.ts
Labels: pr:ready-for-review

#1560 [Epic] Anticheat runtimes (EAC and BattlEye)
  .gitattributes
  electron/__tests__/runtimes/test_data/ArchiveWithSubfolder.tar.xz
  electron/__tests__/runtimes/test_data/TestArchive.tar.xz
  electron/__tests__/runtimes/test_data/github-api-heroic-test-data.json
  electron/__tests__/runtimes/utils.test.ts
  electron/constants.ts
  electron/launcher.ts
  electron/logger/logger.ts
  electron/main.ts
  electron/tsconfig.json
  electron/types.ts
  electron/wine/manager/ipc_handler.ts
  electron/wine/manager/types.ts
  electron/wine/manager/utils.ts
  electron/wine/runtimes/ipc_handler.ts
  electron/wine/runtimes/runtimes.ts
  electron/wine/runtimes/util.ts
  package.json
  src/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/screens/Settings/components/WineExtensions/index.tsx
  src/screens/Settings/components/WineSettings/index.tsx
  src/screens/Settings/components/index.tsx
  src/screens/Settings/index.tsx
  src/types.ts
Labels: pr:ready-for-review

#1559 Fix: Don't 'handleProtocol' if mainWindow doesn't exist yet
  electron/main.ts
Labels: pr:ready-to-merge, pr:ready-for-review

#1568 Clean up `runWineCommand` and other functions in `launcher.ts`
  electron/games.ts
  electron/gog/games.ts
  electron/launcher.ts
  electron/legendary/games.ts
  electron/main.ts
Labels: pr:ready-to-merge, pr:ready-for-review

#1580 [Fix] Delete duplicate ThemeSelector element
  src/screens/Settings/components/GeneralSettings/index.tsx
Labels: pr:ready-for-review

#1589 [Fix] Extract runtimes properly
  electron/wine/runtimes/runtimes.ts
Labels: pr:ready-for-review

#1583 [Windows] Prompt for Visual C++ Runtime installation when not found
  electron/main.ts
  electron/utils.ts
Labels: pr:ready-for-review

#1590 [Fix] Beta 2 Fixes
  electron/gog/library.ts
  electron/main.ts
  src/components/UI/ActionIcons/index.tsx
  src/components/UI/SearchBar/index.tsx
  src/components/UI/Sidebar/components/QuitButton/index.tsx
  src/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/helpers/library.ts
  src/screens/Game/GameSubMenu/index.css
  src/screens/Library/components/GameCard/index.tsx
  src/screens/Library/components/GamesList/index.tsx
  src/screens/Library/components/LibraryHeader/index.tsx
  src/screens/Library/index.css
  src/screens/Library/index.tsx
  src/screens/Settings/components/AdvancedSettings/index.tsx
  src/state/ContextProvider.tsx
  src/state/GlobalState.tsx
  src/types.ts
Labels: pr:ready-for-review

#1608 Fix virtual keyboard keypress
  src/components/UI/SearchBar/index.tsx
  src/helpers/gamepad.ts
  src/helpers/virtualKeyboard.ts
Labels: pr:ready-to-merge

#1595 [Fix] Update dualsense controller mappings
  src/helpers/gamepad_layouts/ps.ts
Labels: pr:ready-for-review

#1597 Don't show update notification after uninstalling a game with available updates
  electron/gog/library.ts
  src/screens/Game/GamePage/index.tsx
  src/screens/Library/components/GamesList/index.tsx
Labels: pr:ready-for-review

#1600 [Fix] Show Tools EOS Overlay button for Epic games only
  src/screens/Game/GameSubMenu/index.tsx
Labels: pr:ready-for-review

#1611 [General/Hotfix] Store default steam path on change
  src/screens/Settings/index.tsx
Labels: pr:ready-for-review

#1606 [General/Hotfix] Fix gog games not launching via protocol
  electron/main.ts
  electron/protocol.ts
Labels: pr:ready-to-merge

#1615 [Fix] Esync/Fsync toggle buttons for Proton
  electron/launcher.ts
Labels: pr:ready-to-merge, pr:ready-for-review

#1603 Refresh recent games when game is launched + no longer sort them on a per-store basis
  electron/main.ts
  src/helpers/library.ts
  src/state/GlobalState.tsx
Labels: pr:ready-for-review

#1618 [Fix] Correct EGL Sync helpbox vertical orientation
  README.md
  madrepo.sh
  rauldipeas.sh
  src/screens/Settings/components/GeneralSettings/index.tsx
Labels: pr:ready-for-review

#1620 [Fix] Runtime toggle logic fix + GameMode message for Flatpak
  electron/main.ts
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/screens/Settings/components/OtherSettings/index.tsx
  src/screens/Settings/components/WineExtensions/index.tsx
  src/screens/Settings/index.tsx
Labels: pr:ready-to-merge, pr:ready-for-review

#1627 [GOG setup] Fix invalid executable paths
  electron/gog/setup.ts
Labels: pr:ready-to-merge, pr:ready-for-review

#1623 [Fix] Pass `runner` in `callTool` IPC call
  electron/main.ts
  src/screens/Settings/components/Tools/index.tsx
  src/screens/Settings/index.tsx
Labels: pr:ready-to-merge, pr:ready-for-review

#1629 [UI] on screen keyboard theming
  src/index.css
  src/themes.css
Labels: pr:ready-for-review

#1631 [Fix] Quote util functions
  electron/__tests__/utils.test.ts
  electron/utils.ts
Labels: pr:ready-for-review

#1637 [Fix] Run winetricks with spawn
  electron/logger/logger.ts
  electron/tools.ts
Labels: pr:ready-for-review

#1622 Fix stale state of games in Recently Played list
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/screens/Library/components/GamesList/index.tsx
  src/screens/Library/components/RecentlyPlayed/index.tsx
  src/screens/Library/index.tsx
  src/screens/Settings/components/GeneralSettings/index.tsx
  src/state/ContextProvider.tsx
  src/state/GlobalState.tsx
  src/types.ts
Labels: pr:ready-to-merge, pr:ready-for-review

#1635 [UX] Prevent Display from sleep when playing a game.
  .github/workflows/draft-release-linux-beta.yml
  .github/workflows/draft-release-mac-beta.yml
  .github/workflows/draft-release-win-beta.yml
  electron/main.ts
  electron/tools.ts
  public/locales/bg/translation.json
  public/locales/ca/translation.json
  public/locales/cs/translation.json
  public/locales/de/translation.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/et/translation.json
  public/locales/fa/translation.json
  public/locales/fi/translation.json
  public/locales/fr/translation.json
  public/locales/gl/translation.json
  public/locales/hr/translation.json
  public/locales/hu/translation.json
  public/locales/id/translation.json
  public/locales/it/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/ml/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/pt_BR/translation.json
  public/locales/ru/translation.json
  public/locales/sv/translation.json
  public/locales/ta/translation.json
  public/locales/tr/translation.json
  public/locales/uk/translation.json
  public/locales/vi/translation.json
  public/locales/zh_Hans/translation.json
  public/locales/zh_Hant/translation.json
  src/components/UI/ActionIcons/index.tsx
  src/components/UI/Header/index.css
  src/components/UI/SearchBar/index.tsx
  src/screens/Library/components/GameCard/index.css
  src/screens/Library/index.css
  src/state/GlobalState.tsx
Labels: pr:ready-for-review
