Repository Heroic-Games-Launcher/HeroicGamesLauncher, pull requests merged in 2023-08, with the labels that each got.

#2929 [Fix] Fix three-dots menu closing when hovering certain items
  src/frontend/screens/Game/GamePage/index.scss
Labels: pr:ready-for-review

#2930 [Fix] Installation of EOS Overlay
  src/backend/launcher.ts
Labels: pr:ready-for-review

#2933 [Fix] Alignment of current download component when sidebar is collapsed
  src/frontend/components/UI/Sidebar/components/CurrentDownload/index.css
  src/frontend/components/UI/Sidebar/components/CurrentDownload/index.scss
  src/frontend/components/UI/Sidebar/components/CurrentDownload/index.tsx
  src/frontend/components/UI/Sidebar/index.scss
Labels: pr:ready-for-review

#2629 Refactor legendary setup
  src/backend/launcher.ts
  src/backend/main.ts
  src/backend/storeManagers/legendary/setup.ts
Labels: pr:wip

#2918 [Tech] Type-check Legendary commands
  package.json
  src/backend/launcher.ts
  src/backend/save_sync.ts
  src/backend/storeManagers/gog/games.ts
  src/backend/storeManagers/legendary/__tests__/games.test.ts
  src/backend/storeManagers/legendary/commands/auth.ts
  src/backend/storeManagers/legendary/commands/base.ts
  src/backend/storeManagers/legendary/commands/cleanup.ts
  src/backend/storeManagers/legendary/commands/eos_overlay.ts
  src/backend/storeManagers/legendary/commands/import.ts
  src/backend/storeManagers/legendary/commands/index.ts
  src/backend/storeManagers/legendary/commands/info.ts
  src/backend/storeManagers/legendary/commands/install.ts
  src/backend/storeManagers/legendary/commands/launch.ts
  src/backend/storeManagers/legendary/commands/list.ts
  src/backend/storeManagers/legendary/commands/move.ts
  src/backend/storeManagers/legendary/commands/status.ts
  src/backend/storeManagers/legendary/commands/sync_saves.ts
  src/backend/storeManagers/legendary/commands/uninstall.ts
  src/backend/storeManagers/legendary/eos_overlay/eos_overlay.ts
  src/backend/storeManagers/legendary/games.ts
  src/backend/storeManagers/legendary/library.ts
  src/backend/storeManagers/legendary/user.ts
  src/backend/storeManagers/nile/games.ts
  src/backend/utils.ts
  src/backend/utils/compatibility_layers.ts
  src/common/types/game_manager.ts
  yarn.lock
Labels: pr:ready-for-review

#2939 [Browser]: handle before unload event properly
  public/locales/en/translation.json
  src/backend/storeManagers/storeManagerCommon/games.ts
Labels: pr:ready-to-merge

#2950 [GOG]: fix issues with missing games metadata
  src/backend/storeManagers/gog/library.ts
  src/common/types/gog.ts
Labels: pr:ready-for-review

#2567 Add support for installing and enabling DXVK-NVAPI
  public/bin/linux/vulkan-helper
  public/locales/en/translation.json
  src/backend/api/wine.ts
  src/backend/config.ts
  src/backend/launcher.ts
  src/backend/main.ts
  src/backend/tools.ts
  src/backend/utils/graphics/vulkan/index.ts
  src/common/typedefs/ipcBridge.d.ts
  src/common/types.ts
  src/frontend/screens/Settings/components/AutoDXVKNVAPI.tsx
  src/frontend/screens/Settings/components/index.ts
  src/frontend/screens/Settings/sections/GamesSettings/index.tsx
Labels: pr:ready-to-merge

#3007 [FIX]: remember if window is maximized
  src/backend/main.ts
  src/backend/main_window.ts
  src/common/types.ts
  src/common/types/electron_store.ts
Labels: pr:ready-for-review
